-- require('zephyr')
--require('treeSetup')
require('colorSetup')
require('galaxySetup')
require('telescopeSetup')
require('sagaSetup')
require('lspSetup')
require('cmpSetup')
require('troubleSetup')
require('nvimTreeSetup')
require('dapSetup')
