#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DP-2 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Vivaldi-stable desktop='^2'
bspc rule -a Clash-verge desktop='^9'
bspc rule -a discord desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Notifications
/usr/bin/dunst &

# Wallpaper
feh --bg-fill /home/eric/Pictures/gruvbox-dark-rainbow.png &
# nitrogen --restore &
# Dex
# dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
dex --autostart --environment bspwm &
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
sh ~/.config/bspwm/scripts/low_bat_notifier.sh &

fcitx5 &

xfce4-clipman &

jetbrains-toolbox &

gnome-keyring-daemon -s --components=pkcs11,secrets,ssh &
# Bar
sh /home/eric/.config/polybar/gruvbox-by-bitterhalt/launch_bspwm.sh &
