#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor DP-2 -d 1 2 3 4 5
# bspc monitor HDMI-0 -d 6 7 8 9 10
bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Vivaldi-stable desktop='^2'
bspc rule -a Skype desktop='^8'
bspc rule -a Clash-verge desktop='^9'
bspc rule -a discord desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Launcher state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a '*:*:Plasma' state=floating layer=normal

bspc rule -a dropdown sticky=on state=floating hidden=on

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

# leave place for plasma bar
bspc config bottom_padding 45

#
# Autostart

# bash ~/.config/bspwm/scripts/autostart.sh &

picom -b &

kitty --class dropdown &
# sh /home/eric/.config/polybar/gruvbox-by-bitterhalt/launch_bspwm.sh &
